
from selenium.webdriver.chrome.options import Options
from selenium import webdriver
import time
import os
import shutil

chrome_options = Options()
chrome_options.add_argument('headless')
chrome_options.add_argument('window-size=512x1080')
#driver = webdriver.Chrome( options= chrome_options )

def main( url , file_nm ):
    '''
    chrome_options = Options()
    chrome_options.add_argument('headless')
    chrome_options.add_argument('window-size=512x1080')
    driver = webdriver.Chrome( options= chrome_options )
    '''
    try:
        driver.get( url )
        # 스크린샷 전에 시간 두기(로딩이 느릴수도 있으니)
        time.sleep(2)
        # 창 최대화
        driver.maximize_window()
        # 스크린샷 찍기
        driver.save_screenshot("C:\\ncnc_class\\test20240209\\"+file_nm+".png")
        # 종료 (모든 탭 종료)
        #driver.quit()
        print("### capture complete")
    except Exception as e:
        print('### error msg :: ', e)
        driver.quit()



def list():
	_list = {
'http://ticket.linkoo.co.kr/ticket/use/?num=AAZDFLVQGP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ABPUWYHOQF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ABTUQSIXKQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AFJKDLIKRZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AFKBOONION'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AIELYHOMFB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AKQLXWVGFP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AMBFXAMXPY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=APGMANJTIS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AQEHSZJLUO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AUNVMUOFWY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AWRXKVODUM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AZDHXHCQOY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AZPKKAKOYJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BAKSNLCMNI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BBFXMKVDCD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BDGNHYGVXD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BDTUGJVWVJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BIHRCZQYJV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BLXVJXPQCW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BRJUCCEHHY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BUBZIIMFFL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BWZUVWVPPQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CATILONKZT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CDJRWNJGOY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CFWHRRBYCZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CHCNAANDRW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CIXOQIJFVJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CPFHCWKVGM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CQTMNSHTOB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CRCOKCNDRU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CYSYGJXGFR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CZRQZFBILA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DBFKTXXWOB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DCMBERABTT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DEMHESWRPY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DFGRRETENN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DIHRSASLSL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DOHLWDJPIF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DOMYFYAPSJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DQALHMGZZP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DRJIIMWVBW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DWAPDDNJOG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DXZXLBXQLB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EASQBXYZTU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EBVMQQHJAH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EBYQFEUBSD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EDXSFMXGDW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EFHFJJPITN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EFJBABFJWO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EKIKPSXSEJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EPOBOGGGOA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EQISZNHRPZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ESCWQMECIL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EWYLAJJHAT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FBRIJCBWTH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FCPRSNSQJI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FCSJBBKTMS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FDGHIQKKWF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FGCGFSJUBA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FGTEZIBVXQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FHPRFONSVM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FKHWUHRZWG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FQRXDVSPHB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FXBPUMOPZV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GHMWOXAEDO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GJBKLMJTKQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GJWOPHFRHA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GPVHTYPYVA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GQQSPOMOGN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GRDYSLYCQV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GUHRCJILAW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GUNAZUSNNN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GUSSSZPBMD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GVVQFDLIOF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GXVPYLAFOW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HGGEHJLPLP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HKYUGHHZJC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HTZKLFXTXG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HXJDVLUZNS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HYAOTLPUNH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HYRRXTCVAC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IBPSLPJCJO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IEZHISUFYV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IFEDOBTYGZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IHKBTFEVSZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IOMDSHADVQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IQLCOFSWPL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IRSHKYOGFU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ISLOXJTCEO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IUGEULPUKS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IXTBXFMADI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JAYXLKDDUY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JICVPKYPKO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JQLAYCOZHQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JRMDAILCXW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JZKCTBWFMV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KBDKIIVYXP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KBWIHTYQAW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KFMGPTBYZP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KILDLWKFGW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KJIGCGTHAK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KODZVANFVQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KOZVZYMZSG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KPBDSTPLIP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KWIQSHXKMZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KWWEZAEVQR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LBWIMASUAT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LISIZHKZOL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LJUCSNHCUD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LTIYEXEJNF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LUGRESYYLI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MAJLIAAKHL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MHJDFWHKWM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MIJAJCYZQH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MKRWFHNDFN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MLFEJIOCWW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MMEWKGZSOS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MMTAGQJVCE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MOFPXHAIGD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MOVPODISWP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MPEOQQRJKQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MRQXZBMPQC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MTRSMGVYJO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MWDZZWGLGX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MXBUSEJHJK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MXUPFGOKBC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MYWDTIWHTE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NDWDXTRJFT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NFUCZDAMES'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NGFFTWIOLY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NIJXJEIGZS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NLKXLRQHMV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NSLSRXGGJW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NSYZBWQMQY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NVIUEFAZWT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NXFKPGLZGT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NXWGCAPUBM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NXZPNOGIXG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OGBDGQRNIA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ONNNDCAHPG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OTDDRDPPLS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OTOFMQYBJW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OUBQVAJVIB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OUTFYEAUDA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OVSZRXZLGP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PGXSKNSXGF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PNPGLDROVC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PQICBNBWBG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PSUFZFMHLR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PVAXNFJVNN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PWZPIDRAPP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QEUEWKALDH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QGQRFGLRNT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QKVKPKYWSF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QONIEOAUTQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QVFQMAJOKF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RCMRYYIASO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RCQDUDGKJV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RIKJKEOVRJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RKBBDBUBJU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RKZZJVOVAE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RSLPEVBITR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RUBMUQVRTT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RXXRIFEGQM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RZUFAFOMNP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SBLIHWWDCI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SCOGODIVHL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SCRQJFEEZU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SFRALZWNVF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SIHHOLOWUR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SLPZOCGLUS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SMIFUSMSDY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SNTJVTJVXK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SOWLVLGPOH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SQRSGHRNPG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SQVEQQJXKX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SREMSNLPEW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SWGBOZBGVB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TGSXCSYZLZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=THPQVPVURI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TIHFDBTVQT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TLVLBLZBEW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TPCWBGXCEF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TQWTXKNIXL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TSNMPSMXRT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TVGYTJPIZJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UAHQGIRFAR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UIRBBQVRLA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UMHGYNBXMT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UNSTLCXTAU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UQTCBEDUJT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UUXJAUCXNM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UYRGDCPDUO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UZOUVQTPZU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VDUSLKNXTT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VHYEGGJYCW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VIDBAKTRMK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VJDPEEKADI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VJOPOWPRXO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VKWVPQDFIF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VLTQTROMBE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VNPXNSWJQJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VOKCTSCWVH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VRSNWYFOUB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VTFYUTIKAM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VUDCNWYCUU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VUKDKJFOAC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WCEGRRXUXO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WHGJCRVGXY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WITHYDASEY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WMPTBRSWNM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WNXAYQMOIT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WOFMYTYDED'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WOHNVPDGEF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WQFEWSZAVS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WROJMJWHPI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WRYQOWQKGK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WSNZORWAVW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WVGWQXCJJS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XCUVMNXAJV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XCYCDASIGD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XEJACETTPP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XGZMOQKPVT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XIREFDCFYS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XLLFHDMURW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XMZJXRQPPM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XRAPEMWOSQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XRXJTUDUXF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YAOKKVLOGM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YBXPMRUXOB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YDLKZNAPIA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YFUABRPBFT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YJHHYXCOVP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YOFWTYDELU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YTMVYWSEYI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YVLYUWWYSM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YXXOQVVYRI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YYURBYWXQV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZDIFWBCDMH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZLFQDKOMXR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZOICMVUCWT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZZLHIKETQH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ADJSZYUKJL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AEBXJDUKBW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AGQZPTZFND'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AHPWDKOCBS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AKIZPEFICX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AKQEEGWBNN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ALFTIDEULP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AMVYMIJUAY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ATSYWPOFCZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AUVIDUDKDY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BAZWTSTNAP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BDUJGZXWHX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BFTVVTMJPH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BHMLVDQPRJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BJTXAMIIOX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BLEXFWAYEE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BSPPMNTATE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BTBESUAPKL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BUDWCUKUJJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BVMKDPGYOY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BZHAOSHGOC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BZULKDJDAO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BZZHPHHTKR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CGRQRZCKTM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CGUUIQXTIP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CHEXCTJXIQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CHSCGPRKJO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CLYWVPLTVY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CMDWRLLCTL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CRMXGAINPH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CRSOTQZZIC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DBOTRORJVH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DEPZXARJAS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DGUQWZNAPU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DJBIXCZWPT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DJOIWDBHWT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DJUMYLUMZB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DKTKSFCMJR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DLMHZXHWTT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DMDYHCOAUL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DSJTPXOHJK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DVKOFRDBGJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ECVECSLDRA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EEJVYLZPER'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EFBJJZGXUO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EIXVPUBUOM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EJCSMTGSWM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ENMKWIRPTY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ESWYMNPBMD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ETQUMVNJNE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EWNUVRPUAC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EWSRGQSYQP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EXAXXWQCCS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FDRKGDPGLC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FFTHAJFNBH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FLLRCRQFXR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FQFPJWICDR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FQYSUBIJJW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FSBKVCZAYJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FUNAUXNGET'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FYRFWIVFGL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GAVEGQNFSW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GCUKJNQTVB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GDZCZBBIZI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GGXWRWCYNM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GIJVVWTLMS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GJEECTHTVS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GLKVJCCAXO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GMCDJFQLWG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GNFTMDONON'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GPUHFHGCII'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GTIQSXMLLG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GUWQXGLEJA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HFACNYVAJV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HIWXZZHPHF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HLUOOAIJAB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HMKYAVESEZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HOEUPYRFYC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HRMMWLXXJD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HSHKUINYFN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HUVFUUFHRY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ICVHRCGUIB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IEGYDHNOGV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IEKVMGTMDT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IJMWCAAMWU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ILLZGRWUQQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IMIZOFYPXH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IMNVTDDXTA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IQSYUHIXXX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IROPYCHPWV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ISYBJCDBCX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ITCASGGXMZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IUMIATWFDV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IWIRHDTTAR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IZMGZPCBRE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IZOEUHZYZX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JCZISBYDIS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JDBJVZPWUJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JHJKGVVCPC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JHXWACSZGQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JJZGSTPICC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JKTENWHVME'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JMCKNMTFWA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JRIVQOGPXO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JRPEWEONDN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JTHZUUCLKN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KFIIBPMLAK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KGHRUWMDVG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KGVUDCQGOK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KJAJNPKRPY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KREPETKIKV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KVJZYQOTXB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KVQVMRORBI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KWBESAHONJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KYMSCYKOUO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LFZICMRJAJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LGRERRTTIM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LPYBQEWNCP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LRJBCYQWOY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LTOXWGLJVY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LXKYJHSTBN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LXSFAOAZZC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LZAFJGQFLJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MEZTQQIGCN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MFWCLUAOKP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MHJNFFZDID'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MIDMKDGIEO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MJHWHDEAJK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MLFSJQRFWS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MOOPVNMJTE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MRABSNYZQP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MRNPERFMAO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MZHQBKPTHC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MZQQKBOJVL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NHMHGNHVQR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NLLVCMPGGK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NPCBETRSWR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NTPSVTNLDL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NWRFXDTBDL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NXLFTYSAOD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OELOYZQTGX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OFURRKWNQS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OGDYHGNDCK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OKMOCZOOFC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OLWMBEVMTY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ORJGPWWKGM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OURLNVHZNL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OVXDVXTRZC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OXDGDWZRPO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OZQZEMAOUB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PAMJBKCNXM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PANSFDQAVM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PCIHVIZDZE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PDJXJMQLYA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PDPMZGPUWJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PFLQCLTRIF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PQDMQJWNFW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PRDNOUPWEE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PUXZSWMNQY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PXXTLOLKUB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PYPKICSZOF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PZMBXPFBPB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PZOCHXREBJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QBSPYMOEQW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QCYNUGIFRU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QDSYNOGSON'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QFCUKWQNJW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QJTOOQOUAW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QRPUKGRFFH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QTSWPNRIYP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QTVMNAALVU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QXAJTZDQUN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QXEBAHWCGE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QXFOHVKXXC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QXIPYQXWRQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QYFKVJSILQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RBSMNXBBRE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RFYBHZZHEW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RGTLFQCKFY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RQIITZANNR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RRFSIGJDSG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RTDZXWIYFG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RYXNFOOMTI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RZFEYWXGYR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SBIWVWANPT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SDXURBXWQS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SGSLAULYWD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SGYJPQMWKA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SIORMJDVOM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SKNTEHSSGP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SLTGVODBKG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SPXMWXVKJS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SQNQCSXMPA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SUMCCIVXLL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SVDRHWGSSL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SVUSYESONV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SWBBWCASLV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SWBVWXERGH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SWJCIVSOSO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TBBQYDFTJX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TCLPDAVKIL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TFXCECFRNM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TIGCMDEOYN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TKPXXUXFRL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TMOATRBASZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TSBCSDGLZK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TSVYDOIVXM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TTMSAYSYUY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UAWGEMZUMQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UDJXVUACTD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UEJMXQJRIO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UFEWMOJRNG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UGIKSYLKRF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UHPTFFLHCZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UIPTTIJYNM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UJFXEQMLCU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UJRIWCSIWX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UKWKPFEWGW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ULMSDVNMFY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ULWSXJGORE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UPZCVCFIGO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=URZJLOOUZH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=USVCLMPHJQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UUQFWWOMEB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UWNWFWSAET'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VCLTSKQDPD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VFAJAKQBDR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VFIXWAVXYH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VJUHWBWYRE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VOQUJFOQQH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VROSTJZHGM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VSRKODYVDM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WAFBQBNJWJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WBHUIRNGFB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WMGPXYDJWK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WNRIZAETDZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WORHVPEXOH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WPNYCDNHNI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WQNYHOUJNW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XAQEFIUAZB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XAZPHYARBC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XCHABRHEIA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XEMBXAZVPI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XETMMPFEHE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XIODSFGQKA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XJMKOWBNAF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XLORGLMJQP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XNYNMCTMQV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XOXCBVFGEP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XTNJDIHTZY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XULBLOMOSU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YBCWYAQYMC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YBQBYPLDYO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YEBYBKSDSJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YIGBWCHBWB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YKTMBJQPNO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YMXAAOYRTR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YSNGKVXARJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZGCHNWPMOI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZQOVNFHMLI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZTMXSICIIY'
    }
	return _list




def getFileList( _path ):    
    __list = os.listdir( _path )    
    list = [ _path+'\\'+X for X in __list ]
    return list


_path1 = 'C:\\ncnc\\배스킨라빈스_패밀리 아이스크림'
_path2 = 'C:\\ncnc_class\\test20240208_back\\'


__list = os.listdir( _path1 )    
print(__list)




for j in __list:
    org_path = _path1+'\\'+j
    list2 = getFileList( org_path )


    for i in list2:
        print(i)
        
        file_nm = i.split('\\')[-1]
        shutil.copyfile( i, _path2+file_nm)
        
        
        
             
    

