
from selenium.webdriver.chrome.options import Options
from selenium import webdriver
import time

chrome_options = Options()
chrome_options.add_argument('headless')
chrome_options.add_argument('window-size=512x1080')
driver = webdriver.Chrome( options= chrome_options )

def main( url , file_nm ):
    '''
    chrome_options = Options()
    chrome_options.add_argument('headless')
    chrome_options.add_argument('window-size=512x1080')
    driver = webdriver.Chrome( options= chrome_options )
    '''
    try:
        driver.get( url )
        # 스크린샷 전에 시간 두기(로딩이 느릴수도 있으니)
        time.sleep(2)
        # 창 최대화
        driver.maximize_window()
        # 스크린샷 찍기
        driver.save_screenshot("C:\\ncnc_class\\sim\\"+file_nm+".png")
        # 종료 (모든 탭 종료)
        #driver.quit()
        print("### capture complete")
    except Exception as e:
        print('### error msg :: ', e)
        driver.quit()



def list():
	_list = {
'http://ticket.linkoo.co.kr/ticket/use/?num=ADYCKPZADN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AFMAJYXIVQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AJOKOKTHPP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ANTLYDOWPF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AOKDZPBZSW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ATMFWJUTZI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=AZBPJVOSCP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BANKRJCHNG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BAZBGAUKAB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BCPFKXWLXI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BFMJAWKUTN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BGFHCZJJHX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BHWYNSTVQC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BISSSAMZPK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BNLKBLZIMX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BTQCRMJURY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BVOQOJVVCX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=BXECJCRXLO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CFBWFKBIEL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CISRAQAORT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CMDHWFYPVS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=COSBSOJKBU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CPKTRZTRDX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CRRIAAQEQX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CSCVYQUFJD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CUJSSPDPMS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=CYDYNQEKOY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DHUOHYTBUH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DISRWSGSHI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DKIKUECZLA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DMNPNGLLBW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DTKZYIASYV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DTMIHWKTWF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DWOWMHJWEK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DXMRUNTJOH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=DYUIQGYANT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EBCMTMPCVY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EFLAJFVRXI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ETPGFUGBNA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EWSIXUUUGL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=EZSVVVWFGL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FFSAMPDIQN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FKIYPMEWTS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FMNJYUZVCJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FOGDWDRMVR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FOQDTMKOUE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FOXWMSCPUL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FQLMKNSYNK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FVRGITULRV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FWGTLYZDNK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FXCRAQWLMD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FXQSOSMLOV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FYVNZNSPPS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=FZKPRERVVS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GDAESKSRXU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GFDMEGYACL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GHTGCXNYCH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GIJJNXTOYG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GYIKBUNAXL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=GYWYDDXIMT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HGNMQLXPIQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HIHMMMESLL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HPGYAJARBX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HPHIBAGBJZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HRKXSAFJYS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=HVFTPURJFO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IHXMBEDHQS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ILFOYURARR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ILYOFNRVQL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=INFYCKKHRE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=INJEWYDWDJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IPDYZSUDMQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IPFOVTQMKA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IRYWKZLHBD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=IZHIHBBBSC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JEBGXPQOCW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JFOQYHAPRQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JFXSESFUQM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JHVJFTLTEE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JHYBELEZQH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JJCZAVMAWX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JPJEEQOIPU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JSLWHVVWDV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JTUULYRWOK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=JTYDTDLYPS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KCGHNYCHPP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KJSNHRJMDG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KKZNULWRQW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KMBHEAMQOE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KNAYHKWPDH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KOOIAIOFYL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KSSLLJHHSK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KTRTLDTXGK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=KZSKXMJNMD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LBVLOODRBB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LQEIPUXIAG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LUMQMUXZPK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LVBXRLNGUW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LWLFBZVIYY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=LXKYGGKXLZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MBLYDLXFKP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MHSGOENRLU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MJYBMWINNY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MKDVAKIJZB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MNIZAWIEPK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MTBDQSJAVJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=MWCENYMMFV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NACEPNJWXP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NCRCMKNFJS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NKKMQHFFIT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NNYBWLLANG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NSRICIOTPP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NWFFFGXITK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=NXKMRJWGBP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OBPQEVPBDE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OBZGHALYVI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OCWXGWEAKK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OFKGWXJOVW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OMUEKPBHIB'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OSOIFBTBFH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OTEYNZOWFR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OTQGJSGWNE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OUUDTMARUJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OVHGUOBHFU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OVQPVLLHPZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OVRQAFDLVZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=OYQAUJHXAS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PAFDZSEPKI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PBIWBCZKZT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PGBRTTNAXY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PGZGOBRMZX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PJTDRPRKGF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PJTGXTZRIP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PJTQWTOHBC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PKNAGBYLDV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PMXKJLBBBF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PNANCBQBJY'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PPVPSJFBQE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PSWHUZFDUM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=PZAUJODTFH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QCZHNVNVOT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QEPQPDDLPL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QEPUTNSNIN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QHYMNPXHOU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QKDLFNHDIX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QPMFPUCLAC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QRDWLBJLVA'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QULRYXAACL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QVLGDJYYPG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QYYDJMXVPN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=QZHDZICXLL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RAUKGHSNQR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RIYHTTTTBK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RJQQYYAIVL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RMCUIELVBT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RTEQJMMPKU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=RXSBFDISJT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SEYQKMZLUI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SFBSZIQJXM'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SFXPWRKBNP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SHNTSHMXBN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SHYTKTPIOO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SMTUWHEOMO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SNLHNOPUSF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SUADHYBDJU'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SWUFLKDOQS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=SZRCJJNHJH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TCLKWGPBCO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TJNOEQQSTP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TMKONQLFYV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TOPRSHEOGW'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TRSCXOLMCQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TXEUMWGEPE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=TZWVJBMKQK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UAIJGNBDQT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UDOIYSXYHX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UETPCHCQAJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UFKPCPIBJL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UFOZKZAAYT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UHVPANVBRF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=UPJWDYBDCT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=URWIGTMJHL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VCJONSLUQQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VJGJXJDNES'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VKNOPDHBWX'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VNSSOZPSTQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VQPJKTPYKV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VVOVEYWWCF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=VYOYYILQNH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WADLZYRBJH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WAZWFLLMKD'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WCMQBZUCHS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WPINFTLNZJ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WTPNQSPWGG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WUVFJSPWHS'
,'http://ticket.linkoo.co.kr/ticket/use/?num=WXBGAGPKBH'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XAKTRJDTXZ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XBPNWIMIVF'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XFDYNDHKZI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XIIWQSOZGI'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XJLILWDLEC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XNKGOXKYUL'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XWVSLWJEIQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=XYTQSSGXNP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YEZOHKDBII'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YLKHBTLKKR'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YQZFNLZCAQ'
,'http://ticket.linkoo.co.kr/ticket/use/?num=YTFZIYAFAG'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZBCMUOLRTK'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZBFWJIFERN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZDZXGHUFDO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZFNJZIJGDV'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZFNSZINFWO'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZJJJOKNZDT'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZMLMGZGWGN'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZNFPUFRIVC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZNXJEKREQE'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZSNOABCFWP'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZVDHAREXLC'
,'http://ticket.linkoo.co.kr/ticket/use/?num=ZXNFMTGQMF'
    }
	return _list


cnt = 0
for i in list():
    url = i 
    file_nm = i.split('num=')[1]
    print(     i )   
    main( url , file_nm )
    cnt += 1